language: python
install:
  - pip install tox
dist: xenial
python: 3.6  # Use the oldest supported version of python as default.
script:
    - date --utc
    - tox -e $TOX_ENV
matrix:
  include:
    - env: TOX_ENV=lint
    - python: 3.6
      env: TOX_ENV=py36
      after_success:
        - pip install codecov
        # Correct coverage xml for coverage services.
        - >
          bash -c 'set -eux;
          pkg_path=$(find .tox/py*/lib/python*/site-packages/pytest_workflow -maxdepth 0 -type d);
          sed -i "s:${pkg_path}:src/pytest_workflow:g" coverage.xml'
        - codecov -v  # -v to make sure coverage upload works.
    - python: 3.7
      env: TOX_ENV=py37
    - python: 3.8
      env: TOX_ENV=py38
